### ISSUE TITLE
Undefined variable: context in in custom/plugins/RecentlyViewedProduct/src/Service/RecentlyViewedProductService.php (line 223)

### ISSUE THREAD

**Issue by jamapag** [vienthuong/RecentlyViewedProduct#10]
Undefined variable: context in in custom/plugins/RecentlyViewedProduct/src/Service/RecentlyViewedProductService.php (line 223):

`     $this->saveRecentProductCollection(new RecentProductCollection($availableIds), $context);`

Hi, Looks like `$context` is not being  passed to `cleanNotAvailableRecentProducts` method.

**Comment by vienthuong** [comment]
HI @jamapag 
Thanks for the contribution :) I will check and merge it soon
