### ISSUE TITLE
Shopware 6.5 compatibility

### ISSUE THREAD

**Issue by lchhieu** [vienthuong/RecentlyViewedProduct#15]
Do you intend to update to be compatible with shopware 6.5? Since shopware 6.5 have changed a lot

**Comment by vienthuong** [comment]
Yes I will, at some point, but currently I'm quite busy :) If you can give me a hand, I'd absolutely appreciate it

**Comment by LouisEiermann** [comment]
@vienthuong I created a PR for 6.5 compatibility :)

**Comment by dolan1090** [comment]
I use your PR. It display in dashboard but not display at frontend (category page, home page, detail page, custom page ...).
I test with default themes of shopware 6.5.6

**Comment by LouisEiermann** [comment]
@dolan1090 Im sorry, im not sure what you mean exactly :)

**Comment by dolan1090** [comment]
@LouisEiermann My mean the extension still doesn't work.
This is video: https://www.awesomescreenshot.com/video/22001916?key=f7761a58a529a4c436c5b04c4e483099

**Comment by dolan1090** [comment]
Thanks you, it worked.

**Comment by vienthuong** [comment]
I don't ready have much time to maintain the project, but thanks @LouisEiermann for his contribution, it's compatible with SW 6.5 with the next plugin's major version 3.0.0
