### ISSUE TITLE
Recently viewed product cannot saved

### ISSUE THREAD

**Issue by lchhieu** [vienthuong/RecentlyViewedProduct#2]
I got a error when saveRecentProductCollection is called
![image](https://user-images.githubusercontent.com/11382616/146183637-e1b93d2c-f5e6-4488-9e92-fcab9c911080.png)

**Comment by vienthuong** [comment]
Hi @lchhieu I will take a look after the boostday :D

**Comment by lchhieu** [comment]
From my sie, I added `id` column to `recently_viewed_product` table and it worked good.

**Comment by vienthuong** [comment]
> From my sie, I added `id` column to `recently_viewed_product` table and it worked good.

if it's working, could you help me to create a MR to fix it :P

**Comment by vienthuong** [comment]
@lchhieu thanks for your contribution
