### ISSUE TITLE
Shopware 6.4.9 compatibility

### ISSUE THREAD

**Issue by lchhieu** [vienthuong/RecentlyViewedProduct#5]
I got an issue when upgrade to 6.4.9
` Unable to compile the theme. `scss/layout/_scroll-up` file not found for @import: custom/plugins/recently-viewed-products/src/Resources/app/storefront/src/scss/rvp.scss on line 1, at column 0                   `      
Could you take a look?

**Comment by vienthuong** [comment]
Hi @lchhieu 
thanks for reporting it, I will have a look

**Comment by vienthuong** [comment]
I fixed it in the latest comment, could you have a look?

**Comment by lchhieu** [comment]
Everything is good for now, thanks author
