### ISSUE TITLE
Incompatiblity with Themeware

### ISSUE THREAD

**Issue by mfmaut** [vienthuong/RecentlyViewedProduct#6]
When install the Plugin and Themeware is installed:

`Unable to compile the theme "TcinnThemeWareModern". `scss/layout/_scroll-up` file not found for @import: /home/www/<domain>/custom/plugins/RecentlyViewedProduct-1.1.1/src/Resources/app/storefront/src/scss/rvp.scss on line 1, at column 0 Call Stack: #0 import /home/www/<domain>/custom/plugins/RecentlyViewedProduct-1.1.1/src/Resources/app/storefront/src/scss/rvp.scss /home/www/<domain>/custom/plugins/RecentlyViewedProduct-1.1.1/src/Resources/app/storefront/src/scss/base.scss on line 1 #1 import /home/www/<domain>/custom/plugins/RecentlyViewedProduct-1.1.1/src/Resources/app/storefront/src/scss/base.scss (unknown file) on line 967`

**Comment by vienthuong** [comment]
Hi @mfmaut can you check the latest version? I already fix it in the latest commit 
https://github.com/vienthuong/RecentlyViewedProduct/commit/a37034c496a9df9699175905f35092f253d095a4

**Comment by mfmaut** [comment]
Uh, sorry. I ve downloaded the release, now i tried it with the repo itself. it works just fine..
thank you, great work 👍
