### ISSUE TITLE
CMS Block in Shopping Experiences Site-Builder gone

### ISSUE THREAD

**Issue by mfmaut** [vienthuong/RecentlyViewedProduct#8]
Since Version 6.4.10.1 the CMS Block for RVP is gone. 
The block itself is still displayed in the frontend but it has disappeared in the site builder and can no longer be found under Commerce.
Any Ideas? :)

**Comment by vienthuong** [comment]
Hi @mfmaut I will check it

**Comment by mfmaut** [comment]
Thank you :)

**Comment by vienthuong** [comment]
@mfmaut @samkasd Hi sorry for the forever update 😞, could have a look at the latest version if it works with your SW 6.4.11.0 onward?

**Comment by vienthuong** [comment]
closed due to duplicated with https://github.com/vienthuong/RecentlyViewedProduct/issues/9, feel free to reopen if you face any issue
