### ISSUE TITLE
Not compatible with Shopware 6.4.11.1

### ISSUE THREAD

**Issue by samkasd** [vienthuong/RecentlyViewedProduct#9]
Thank you for developing this plugin. It worked fine, until the update.

**Comment by vienthuong** [comment]
@samkasd Thanks for reporting, I will check it

**Comment by vienthuong** [comment]
@mfmaut @samkasd Hi sorry for the forever update 😞 , Im finally have time to update it, could have a look at the latest version if it works with your SW 6.4.11.0 onward?
